[package]
name = "unused-ips-file-generator"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "available-ips-scanner"
path = "src/main.rs"

[dependencies]
clap = { version = ">=4.5, <5.0", features = ["derive"] }
rayon = ">=1.10, <2.0"
